export const DRAWING_REPOSITORY = 'DRAWING_REPOSITORY';
export const DOCUMENT_REPOSITORY = 'DOCUMENT_REPOSITORY';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const AUDIT_REPOSITORY = 'AUDIT_REPOSITORY';
export const DELETE_LOCK_REPOSITORY = 'DELETE_LOCK_REPOSITORY';
export const PERSISTENCE_UNIT_OF_WORK = 'PERSISTENCE_UNIT_OF_WORK';

export const PERSISTENCE_REPOSITORY_TOKENS = {
  drawing: DRAWING_REPOSITORY,
  document: DOCUMENT_REPOSITORY,
  order: ORDER_REPOSITORY,
  audit: AUDIT_REPOSITORY,
  deleteLock: DELETE_LOCK_REPOSITORY,
  unitOfWork: PERSISTENCE_UNIT_OF_WORK,
} as const;
