FROM node:22-alpine AS api

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/tablet/package.json apps/tablet/package.json
RUN npm ci

COPY . .
RUN npm run prisma:generate
RUN npm run build:api

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV API_PREFIX=api

EXPOSE 3000

CMD ["npm", "run", "start:cloud", "-w", "api"]
