import type { ImportTemplateDefinition, ImportType } from '../common/types/production.types';

export const importTypeLabels: Record<ImportType, string> = {
  production_plan: '生产计划',
  customer_product: '客户产品',
  front_parameter: '前段参数',
  back_package: '后段资料包',
  fixture: '治具库',
  abnormal_case: '异常库',
  quality_standard: '质量标准库',
};

export const importTemplates: ImportTemplateDefinition[] = [
  {
    type: 'production_plan',
    label: importTypeLabels.production_plan,
    description: '导入本周或今日生产计划，自动补齐客户和产品基础资料。',
    fields: [
      { field: '计划日期', required: true, description: '格式建议 YYYY-MM-DD', example: '2026-06-15' },
      { field: '周计划编号', required: false, description: '生产周计划编号', example: 'W26-C-001' },
      { field: '销售', required: false, description: '销售或客户经理', example: '演示销售' },
      { field: '客户', required: true, description: '客户简称或全称', example: '演示新能源' },
      { field: '产品编号', required: true, description: '线束产品编号', example: 'HL-DEMO-2001' },
      { field: '产品名称', required: true, description: '线束产品名称', example: '演示电池采样线束' },
      { field: '产品版本', required: false, description: '为空默认 Rev.A', example: 'Rev.A' },
      { field: '工序段', required: true, description: '前段 / 后段 / 通用', example: '通用' },
      { field: '计划数量', required: true, description: '必须是数字', example: 800 },
      { field: '完成数量', required: false, description: '必须是数字，空则 0', example: 0 },
      { field: '生产状态', required: false, description: '待生产 / 生产中 / 已完成 / 异常', example: '待生产' },
      { field: '负责人', required: false, description: '为空默认组长演示账号', example: '前段一组 / 后段二组' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
  {
    type: 'customer_product',
    label: importTypeLabels.customer_product,
    description: '导入客户与产品基础资料，同客户 + 产品编号视为同一产品。',
    fields: [
      { field: '销售', required: false, description: '销售或客户经理', example: '演示销售' },
      { field: '客户', required: true, description: '客户简称或全称', example: '演示智造' },
      { field: '产品编号', required: true, description: '线束产品编号', example: 'HL-DEMO-2101' },
      { field: '产品名称', required: true, description: '产品名称', example: '演示控制器信号线束' },
      { field: '产品版本', required: false, description: '为空默认 Rev.A', example: 'Rev.A' },
      { field: '产品类别', required: false, description: '产品分类', example: '低压信号线束' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
  {
    type: 'front_parameter',
    label: importTypeLabels.front_parameter,
    description: '导入前段裁线、剥皮、端子、拉力、压接等工艺参数。',
    fields: [
      { field: '客户', required: true, description: '客户简称或全称', example: '演示新能源' },
      { field: '产品编号', required: true, description: '线束产品编号', example: 'HL-DEMO-2001' },
      { field: '产品版本', required: false, description: '为空默认 Rev.A', example: 'Rev.A' },
      { field: '裁线长度', required: false, description: '建议填写', example: '820 mm' },
      { field: '剥皮长度', required: false, description: '建议填写', example: '5.0 mm' },
      { field: '端子型号', required: false, description: '建议填写', example: 'DEMO-TER-01' },
      { field: '拉力标准', required: false, description: '建议填写', example: '>= 80 N' },
      { field: '压接高度', required: false, description: '建议填写', example: '1.42 +/- 0.03 mm' },
      { field: '图纸版本', required: false, description: '为空默认 Rev.A', example: 'DRW-Rev.A' },
      { field: '参数状态', required: false, description: '当前有效 / 待确认 / 已失效 / 不一致', example: '待确认' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
  {
    type: 'back_package',
    label: importTypeLabels.back_package,
    description: '导入连接器、装配说明书、孔位图、SOP、成品细节图等后段资料包信息。',
    fields: [
      { field: '客户', required: true, description: '客户简称或全称', example: '演示新能源' },
      { field: '产品编号', required: true, description: '线束产品编号', example: 'HL-DEMO-2001' },
      { field: '产品版本', required: false, description: '为空默认 Rev.A', example: 'Rev.A' },
      { field: '连接器型号', required: false, description: '建议填写', example: 'DEMO-32P' },
      { field: '连接器装配说明书', required: false, description: '说明书名称', example: 'DEMO-32P 装配说明书' },
      { field: '插接孔位图', required: false, description: '孔位图名称', example: 'DEMO-32P 孔位图' },
      { field: '作业流程SOP', required: false, description: 'SOP 名称', example: '后段插接测试 SOP' },
      { field: '成品细节图数量', required: false, description: '必须是数字，空则 0', example: 6 },
      { field: '图纸版本', required: false, description: '为空默认 Rev.A', example: 'DRW-Rev.A' },
      { field: 'SOP版本', required: false, description: '为空默认 Rev.A', example: 'SOP-Rev.A' },
      { field: '资料状态', required: false, description: '当前有效 / 待确认 / 已失效 / 不一致', example: '待确认' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
  {
    type: 'fixture',
    label: importTypeLabels.fixture,
    description: '导入现场治具资料，用于按产品、工序和工位快速查询治具使用与点检标准。',
    fields: [
      { field: '治具编号', required: true, description: '治具唯一编号', example: 'FIX-HV-4821A-CRIMP' },
      { field: '治具名称', required: true, description: '治具名称', example: '高压采样端子压接定位治具' },
      { field: '治具类型', required: false, description: '压接定位 / 插接防错 / 导通测试', example: '压接定位' },
      { field: '客户', required: false, description: '演示客户名称', example: '示例新能源' },
      { field: '产品ID', required: false, description: '可选，填入现有 Mock 产品 ID 时自动关联', example: 'PRD-4821A' },
      { field: '产品编号', required: true, description: '产品编号', example: 'HL-EV-4821A' },
      { field: '产品名称', required: false, description: '产品名称', example: '电池包高压采样线束' },
      { field: '工序段', required: false, description: 'front/back/common 或 前段/后段/通用', example: 'front' },
      { field: '适用工位', required: false, description: '现场工位', example: '前段 A1 压接工位' },
      { field: '使用方法', required: false, description: '治具使用说明', example: '端子进入定位槽后压紧限位块' },
      { field: '点检标准', required: false, description: '治具点检或校验标准', example: '定位销无松动，端子偏移不超过 0.2 mm' },
      { field: '保养周期', required: false, description: '保养周期', example: '每班点检，每周保养' },
      { field: '状态', required: false, description: 'active/pending_review/inactive/abnormal 或中文状态', example: 'active' },
      { field: '关键词', required: false, description: '逗号分隔', example: '压接,定位治具,端子' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
  {
    type: 'abnormal_case',
    label: importTypeLabels.abnormal_case,
    description: '导入现场异常案例，用于组长按产品、工序和现象快速定位处理方案。',
    fields: [
      { field: '异常编号', required: true, description: '异常案例编号', example: 'ABN-HV-PIN-REVERSE' },
      { field: '异常标题', required: true, description: '异常标题', example: '32P 连接器插针方向反向' },
      { field: '客户', required: false, description: '演示客户名称', example: '示例新能源' },
      { field: '产品ID', required: false, description: '可选 Mock 产品 ID', example: 'PRD-4821A' },
      { field: '产品编号', required: true, description: '产品编号', example: 'HL-EV-4821A' },
      { field: '产品名称', required: false, description: '产品名称', example: '电池包高压采样线束' },
      { field: '工序段', required: false, description: 'front/back/common 或 前段/后段/通用', example: 'back' },
      { field: '工位', required: false, description: '异常发生工位', example: '后段 B2 插接工位' },
      { field: '异常类别', required: false, description: '异常类别', example: '孔位插接' },
      { field: '异常现象', required: false, description: '现场现象', example: '导通测试提示 7/8 孔位交叉' },
      { field: '原因分析', required: false, description: '原因分析', example: '孔位图版本未确认' },
      { field: '处理方法', required: false, description: '处理方法', example: '停线复核孔位图并重新插接' },
      { field: '预防措施', required: false, description: '预防措施', example: '上线前由组长确认孔位图版本' },
      { field: '严重度', required: false, description: 'low/medium/high/critical 或 低/中/高/严重', example: 'high' },
      { field: '状态', required: false, description: 'active/pending_review/closed 或中文状态', example: 'active' },
      { field: '关键词', required: false, description: '逗号分隔', example: '孔位反向,导通NG,插针' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
  {
    type: 'quality_standard',
    label: importTypeLabels.quality_standard,
    description: '导入质量标准，用于前段/后段检验项目、标准值、公差和抽检规则查询。',
    fields: [
      { field: '质量标准编号', required: true, description: '标准编号', example: 'QLT-HV-CRIMP-PULL' },
      { field: '质量标准标题', required: true, description: '标准标题', example: '高压采样端子压接拉力标准' },
      { field: '客户', required: false, description: '演示客户名称', example: '示例新能源' },
      { field: '产品ID', required: false, description: '可选 Mock 产品 ID', example: 'PRD-4821A' },
      { field: '产品编号', required: true, description: '产品编号', example: 'HL-EV-4821A' },
      { field: '产品名称', required: false, description: '产品名称', example: '电池包高压采样线束' },
      { field: '工序段', required: false, description: 'front/back/common 或 前段/后段/通用', example: 'front' },
      { field: '检验项目', required: false, description: '检验项目', example: '端子压接拉力' },
      { field: '标准值', required: false, description: '标准值', example: '>= 120 N' },
      { field: '公差', required: false, description: '公差或红线', example: '不得低于标准值' },
      { field: '检验方法', required: false, description: '检验方法', example: '首件三件拉力测试' },
      { field: '抽检规则', required: false, description: '抽检规则', example: '首件必检，过程每 2 小时抽检 3 件' },
      { field: '缺陷等级', required: false, description: 'minor/major/critical 或 轻微/主要/严重', example: 'critical' },
      { field: '状态', required: false, description: 'effective/pending_review/expired 或中文状态', example: 'effective' },
      { field: '关键词', required: false, description: '逗号分隔', example: '拉力标准,压接,首件' },
      { field: '备注', required: false, description: '导入备注', example: '演示数据 / 非真实客户资料' },
    ],
  },
];

export function getImportTemplate(type: ImportType) {
  return importTemplates.find((template) => template.type === type);
}
